second/second/accounts/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
app_name = 'accounts'
urlpatterns = [
    path('filter/<str:status>/', home, name='home'),
    path('persons/', person_filter, name='pfilter'),
    path('create/', create_person, name='cperson'),
    path('edit/<int:id>/', edit_person, name='edit_person'),
    path('profile/<int:id>/', profile, name='profile'),
    path('delete/<int:id>/', delete, name='delete'),
    path('', signin, name='signin'),
    path('logout/', signout, name='logout'),
    path('about/', TemplateView.as_view(template_name="login.html"),name='about'),


# Class Based View
path('language/',LanguageCreate.as_view(), name='language'),
path('language/all/',LanguageList.as_view(), name='alllanguage'),
path('language/<int:pk>/',LanguageDetail.as_view(), name='ldetail'),


]

# path('filter/<str:search>')

second/second/main/urls.py
from django.urls import path
from .views import *
app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('create/<str:cat>/', create, name='create'),

]

# path('filter/<str:search>')

second/second/second/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('main/', include('main.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

second/second/accounts/forms.py
from django import forms
from django.db import models
from .models import Person, Language
from datetime import datetime, date
today = date.today()


class PersonForm(forms.ModelForm):
    #year = forms.CharField()
    documents = forms.ImageField(
        widget=forms.FileInput(attrs={'class': 'form-control'}), required=False)
    photo = forms.ImageField(widget=forms.FileInput(
        attrs={'class': 'form-control'}), required=False)
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}))
    age = forms.CharField(widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your age here'}))
    """ age = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your age here','type':'number'})) """
    dob = forms.DateField(widget=forms.DateTimeInput(
        format=('%Y-%m-%d'), attrs={'class': 'form-control datepicker', 'value': today, 'type': 'date'}), label='जन्म की तारीख')  # ,required=False
    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Email', 'type': 'email'}))
    desc = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Enter Description'}))
    salary = forms.CharField(widget=forms.NumberInput(
        attrs={'class': 'form_sal', 'placeholder': 'Enter your Salary'}))

    # gender =
    # citizen =
    # rooms =
    # language =
    # images =

    class Meta:
        model = Person
        fields = "__all__"
        exclude = ['citizen']
        #fields = ['year', 'first_name', 'last_name']
        widgets = {
            'gender': forms.Select(attrs={'class': 'custom-select'}),
            'citizen': forms.Select(attrs={'class': 'custom-select'}),
            'rooms': forms.Select(attrs={'class': 'custom-select'}),
            'year': forms.Select(attrs={'class': 'custom-select'}),


        }
        labels = {
            'gender': 'लिंग',
        }

        # errors = {
        #     'email':{'required':,'invalid':"Hello all invalid data"}

        # }


class CitizenForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        exclude = ['user']


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = '__all__'
        exclude = ['user']

second/second/templates/create.html
<!doctype html>
{% load crispy_forms_tags %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Person</title>

    <style>
        form {
            padding: 10px;
            margin-top: 10px;
            margin-bottom: 10px;

            border: 1px solid black;
            background-color: gray;
            left: 45%;
            width: 50%;
        }

        .form_sal {

            width: 100%;
            height: 2rem;
            color: green;
            background-color: lightgreen;

        }

        .errorlist {
            color: darkred;
        }

        .container {
            position: absolute;
            top: 2rem;
            left: 25%;
            margin-top: 2rem;
        }
    </style>
</head>

<body>
    <center class='text-success'>
        <h1> Create Persons</h1>
    </center>
    <a class='link' href="{% url 'accounts:pfilter' %}">Back</a>
    <div class='container'>

        {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert" '>
        {% for message in messages %}
        {% if message.tags == ' error' %} <p style="background-color:red;color:white;">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            <h5>{{ message }}</h5>
            </p>
            {% else %}
            <p style="background-color:green;color:white;">
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            <h5>{{ message }}</h5>
            </p>
            {% endif %}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}


        <form method='post' action="" enctype="multipart/form-data">

            {% if form.errors %}
            <div class="alert alert-error">
                <h4>Please fix the following errors</h4>
                <ul>
                    {% for field in form %}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <p><strong>{{ field.name }}</strong> {{ error|escape }}</p>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </ul>
                {% if form.non_field_errors %}
                {{ form.non_field_errors }}
                {% endif %}
            </div>
            {% endif %}

            {% csrf_token %}
            {{form.year}}
            <img src="https://source.unsplash.com/user/erondu/1600x900" width="100" height="25">

            {{form.documents}}
            <div class='row'>
                <div class="col-sm-5">
                    {{form.first_name|as_crispy_field}}
                </div>
                <div class="col-sm-5">
                    {{form.last_name|as_crispy_field}}

                </div>
                <div class="col-sm-2">
                    {{form.age|as_crispy_field}}
                </div>
            </div>
            <label for='id_photo'>Photo:</label>
            {{form.photo}}


            {{form.email|as_crispy_field}}

            <button type="submit" class="btn btn-primary btn-sm m-4">Submit</button>
        </form>

    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

second/second/templates/create_user.html
<!doctype html>
{% load crispy_forms_tags %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Create User</title>

    <style>
        .errorlist {
            color: brown;
        }

        .helptext {
            color: blue;
        }
    </style>
</head>

<body>

    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit'>Submit</button>
    </form>

</body>

</html>

second/second/templates/language.html
<!doctype html>
{% load crispy_forms_tags %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Person</title>

    <style>
        form {
            padding: 10px;
            margin-top: 10px;
            margin-bottom: 10px;

            border: 1px solid black;
            background-color: gray;
            left: 45%;
            width: 50%;
        }

        .form_sal {

            width: 100%;
            height: 2rem;
            color: green;
            background-color: lightgreen;

        }

        .errorlist {
            color: darkred;
        }

        .container {
            position: absolute;
            top: 2rem;
            left: 25%;
            margin-top: 2rem;
        }
    </style>
</head>

<body>
    <center class='text-success'>
        <h1> Create Persons</h1>
    </center>
    <a class='link' href="{% url 'accounts:pfilter' %}">Back</a>
    <div class='container'>

        {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert" '>
        {% for message in messages %}
        {% if message.tags == ' error' %} <p style="background-color:red;color:white;">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            <h5>{{ message }}</h5>
            </p>
            {% else %}
            <p style="background-color:green;color:white;">
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            <h5>{{ message }}</h5>
            </p>
            {% endif %}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}


        <form method='post' action="" enctype="multipart/form-data">

            {% if form.errors %}
            <div class="alert alert-error">
                <h4>Please fix the following errors</h4>
                <ul>
                    {% for field in form %}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <p><strong>{{ field.name }}</strong> {{ error|escape }}</p>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </ul>
                {% if form.non_field_errors %}
                {{ form.non_field_errors }}
                {% endif %}
            </div>
            {% endif %}

            {% csrf_token %}
            {{form}}

            <button type="submit" class="btn btn-primary btn-sm m-4">Submit</button>
        </form>

    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

second/second/templates/login.html
<!doctype html>
{% load crispy_forms_tags %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Person</title>

    <style>
        form {
            padding: 10px;
            margin-top: 10px;
            margin-bottom: 10px;

            border: 1px solid black;
            background-color: lightgray;
            left: 45%;
            width: 50%;
        }

        .form_sal {

            width: 100%;
            height: 2rem;
            color: green;
            background-color: lightgreen;

        }

        .errorlist {
            color: darkred;
        }

        .container {
            position: absolute;
            top: 2rem;
            left: 25%;
            margin-top: 2rem;
        }
    </style>
</head>

<body>
    <center class='text-success'>
        <h1> Login</h1>
    </center>
    <div class='container'>

        {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert" '>
        {% for message in messages %}
        {% if message.tags == ' error' %} <p style="background-color:red;color:white;">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            <h5>{{ message }}</h5>
            </p>
            {% else %}
            <p style="background-color:green;color:white;">
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            <h5>{{ message }}</h5>
            </p>
            {% endif %}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        <!-- THis  if else is for authenticated user and unauthenticated user -->
        {% if request.user.is_authenticated %}
        Welcome {{request.user.username}}

        {% else %}
        <form method='post' action="" enctype="multipart/form-data">
            {% csrf_token %}
            <label for='username'>Username / Email</label>
            <input name='username' id='username' type='text'>
            <br>
            <label for='pass'>Password</label>
            <input name='pass' id='pass' type='password'>

            <br>
            <button type="submit" class="btn btn-primary btn-sm m-4">Submit</button>
        </form>

        <a href="{% url 'main:create' 'teacher' %}">Signup as Teacher</a>
        <a href="{% url 'main:create' 'student' %}">Signup as Student</a>

        {% endif %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

second/second/templates/persons.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Person</title>
</head>

<body>

    {{request.user.first_name|capfirst}} {{request.user.last_name|capfirst}}
    <a href="{% url 'accounts:logout' %}">Logout</a>
    <center class='text-success'>
        <h1> List of Persons ({{filter}})</h1>
    </center>
    {% if messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert" '>
        {% for message in messages %}
        {% if message.tags == ' error' %} <p style="background-color:red;color:white;">
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        <h5>{{ message }}</h5>
        </p>
        {% else %}
        <p style="background-color:green;color:white;">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        <h5>{{ message }}</h5>
        </p>
        {% endif %}
        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}


    <a class='link' href="{% url 'accounts:cperson' %}">Create person</a>
    <a class='link' href="{% url 'main:home' %}">Home</a>

    <form>
        <select name='filter'>

            <option value='All' selected>---- All ----</option>
            <option value='Male'>Male</option>
            <option value='Female'>FeMale</option>
            <option value="Other">Other</option>

        </select>
        <button type="submit" class="ml-2 btn btn-success btn-sm">Filter</button>
    </form>

    <table class="table table-striped table-hover table-condensed table-bordered table-info">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full Name</th>
                <th scope="col">Email</th>
                <th scope="col">Gender</th>
                <th scope="col">Salary</th>
                <th scope="col">Is Verified</th>
                <th scope="col">Documents</th>
                <th scope="col">Image</th>
                <th scope="col">Citizenship</th>
                <th scope="col">Languages</th>
                <th>Action</th>


            </tr>
        </thead>
        <tbody>



            {% for person in persons %}
            {% if request.user.is_verified %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td><a href="{% url 'accounts:profile' person.id %}"> {{person.first_name}}
                        {{person.last_name}}</a></td>
                <td>{{person.email}}</td>
                <td>{{person.gender}}</td>
                <td>{{person.salary}}</td>
                <td>{{person.is_verify}}</td>


                <td><a href='{{person.documents.url}}'><i class="fa fa-eye" aria-hidden="true"></i>
                        Document</a></td>
                <td>
                    {% if person.photo %}

                    <img src='{{person.photo.url}}' height=50 width=50>
                    {% else %}
                    No Image Found
                    {% endif %}
                </td>
                <td>
                    <ul>
                        <li>Citizenship no: {{person.citizen}}</li>
                        <li>Fathers Name: {{person.citizen.father_name}}</li>
                        <li>Mothers Name: {{person.citizen.mothername}}</li>
                        <li>Address: {{person.citizen.address}}</li>



                    </ul>

                </td>
                <td>
                    {% for i in person.language.all %}
                    {{i.name}}
                    {{i.origin}}

                    {% endfor %}
                </td>
                <td> <a class="btn btn-warning btn-sm m-2" href="{% url 'accounts:edit_person' person.id %}"> <i
                            class="fas fa-edit ml-1"></i> Update</a>
                    <a class="btn btn-danger btn-sm m-2" href="{% url 'accounts:delete' person.id %}"> <i
                            class="fas fa-trash-alt ml-1"></i> Delete</a>

                </td>

            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

second/second/templates/profile.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>object</title>

    <style>
        .container {
            background-color: lightgrey;
            width: 70%;
            margin: 1rem;
            padding: 1rem;
            position: absolute;
            left: 18%;
        }
    </style>
</head>

<body>
    <center class='text-success'>
        <h1> {{object.first_name}}
            {{object.last_name}}
        </h1>
    </center>


    <a class="btn btn-warning btn-sm m-2" href="{% url 'accounts:edit_person' object.id %}"> <i
            class="fas fa-edit ml-1"></i>
        Update</a>
    <div class='container'>
        {% if object.photo %}
        <img src='{{object.photo.url}}' width='150' height='150' style="border-radius: 30%;">

        {% endif %}


        <ul>
            <li>Citizenship no: {{object.citizen}}</li>
            <li>Fathers Name: {{object.citizen.father_name}}</li>
            <li>Mothers Name: {{object.citizen.mothername}}</li>
            <li>Address: {{object.citizen.address}}</li>



        </ul>
    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>